# Collision Dataset Exploration

My main goal is to develop a pipeline to evaluate the location data of Toronto Open Data's KSI Collision dataset. 

However, there's alot of variety in the dataset. In order to best evaluate each collision record, I must segment the collisions into categories, and come up with methods to assess the quality of each category of collision.

The focus of the this notebook is to determine how to segment the collisions.

In [1]:
import geopandas as gpd
import pandas as pd

In [4]:
collision_data = pd.read_csv("../data/collisions.csv")
collision_data = collision_data[['collision_id', 'stname1', 'stname2', 'stname3']]
collision_data.head()

  collision_id       stname1      stname2 stname3
0  2006:893184  WOODBINE AVE  O CONNOR DR     NaN
1  2006:893184  WOODBINE AVE  O CONNOR DR     NaN
2  2006:893184  WOODBINE AVE  O CONNOR DR     NaN
3  2006:893184  WOODBINE AVE  O CONNOR DR     NaN
4  2006:893184  WOODBINE AVE  O CONNOR DR     NaN

We segment the collisions based on the values of `stname1`, `stname2`, and `stname3`.

According to the database documentation, `stname1` and `stname2` will typically take on the names of streets (eg. Wilson Ave), and `stname3` will include information about distance and direction from the intersection described in `stname1` and `stname2`, (eg. 80m West of).

However, once we take a look at the dataset, we can see that  `stname1` and `stname2` can also take on values representing addresses (eg. 20 Redgrave Dr). 

We must also watch out for any of `stname1`, `stname2`, and/or `stname3` being null.

In [12]:
collision_data[collision_data['stname1'].isnull()]

Empty DataFrame
Columns: [collision_id, stname1, stname2, stname3]
Index: []

Nice to see that there are not collisions with `stname1` null. Makes my life easier. Now let's check how many of them are addresses.

In [39]:
collision_data[collision_data['stname1'].str.match(r'^40')]

,collision_id,stname1,stname2,stname3
340,2006:899004,40 STORMONT AVE,NaN,NaN
341,2006:899004,40 STORMONT AVE,NaN,NaN
342,2006:899004,40 STORMONT AVE,NaN,NaN
343,2006:899004,40 STORMONT AVE,NaN,NaN
344,2006:899004,40 STORMONT AVE,NaN,NaN
345,2006:899004,40 STORMONT AVE,NaN,NaN
346,2006:899004,40 STORMONT AVE,NaN,NaN
977,2006:927585,400 S JANE ST RAMP S,JANE ST Stre,NaN
978,2006:927585,400 S JANE ST RAMP S,JANE ST Stre,NaN
979,2006:927585,400 S JANE ST RAMP S,JANE ST Stre,NaN
1375,2006:943330,40 KING St W,NaN,NaN
1376,2006:943330,40 KING St W,NaN,NaN
1529,2007:949215,4071 KINGSTON RD,NaN,NaN
1530,2007:949215,4071 KINGSTON RD,NaN,NaN
1531,2007:949215,4071 KINGSTON RD,NaN,NaN
1804,2007:964870,40 WILLCOCKS St,NaN,NaN
1805,2007:964870,40 WILLCOCKS St,NaN,NaN
4101,2008:1079815,40 CLUNY DR,CRESCENT Road,NaN
4136,2008:1079815,40 CLUNY DR,CRESCENT Road,NaN
4137,2008:1079815,40 CLUNY DR,CRESCENT Road,NaN
12443,2016:6000498147,400 NUGGET AVE,NaN,110 m South of
12444,2016:6000498147,400 NUGGET AVE,NaN,110 m South of
12445,2016:6000498147,400 NUGGET AVE,NaN,110 m South of
12738,2016:6001183781,401 C W MCCOWAN N RAMP RD,MCCOWAN RD,NaN
12739,2016:6001183781,401 C W MCCOWAN N RAMP RD,MCCOWAN RD,NaN
13105,2016:6001958569,401 W ALLEN YORKDALE RAMP,YORKDALE RD,20 m East of
13416,2017:7000503905,401 C E VICTORIA PR N RAMP,VICTORIA PARK AVE,NaN
13417,2017:7000503905,401 C E VICTORIA PR N RAMP,VICTORIA PARK AVE,NaN
14347,2018:8000311536,401 C E WESTON RD RAMP,WESTON RD,NaN
14348,2018:8000311536,401 C E WESTON RD RAMP,WESTON RD,NaN
14349,2018:8000311536,401 C E WESTON RD RAMP,WESTON RD,NaN
14350,2018:8000311536,401 C E WESTON RD RAMP,WESTON RD,NaN
14351,2018:8000311536,401 C E WESTON RD RAMP,WESTON RD,NaN
17250,2021:1001488085,401 EB OFF RAMP,KINGSTON RD,26 m East of
17396,2021:1001963083,40 FARNSWORTH DR,FARNSWORTH DR,10 m North of
19058,2024:4000161611,400 MIDWEST RD,GREAT W DR,325 m South of
19059,2024:4000161611,400 MIDWEST RD,GREAT W DR,325 m South of

In [31]:
collision_data[collision_data['stname1'].str.match(r'^[a-zA-Z]+')]

          collision_id            stname1           stname2       stname3
0          2006:893184       WOODBINE AVE       O CONNOR DR           NaN
1          2006:893184       WOODBINE AVE       O CONNOR DR           NaN
2          2006:893184       WOODBINE AVE       O CONNOR DR           NaN
3          2006:893184       WOODBINE AVE       O CONNOR DR           NaN
4          2006:893184       WOODBINE AVE       O CONNOR DR           NaN
...                ...                ...               ...           ...
20450  2025:5000721646  LAKE SHORE BLVD W          FIFTH ST   5 m East of
20451  2025:5000721646  LAKE SHORE BLVD W          FIFTH ST   5 m East of
20452  2025:5000721646  LAKE SHORE BLVD W          FIFTH ST   5 m East of
20453  2025:5000721646  LAKE SHORE BLVD W          FIFTH ST   5 m East of
20454  2025:5001386641            MILL ST  Rolling Mills Rd  6 m South of

[18498 rows x 4 columns]